apiVersion: v1
kind: Service
metadata:
  name: client-svc
  labels:
    component: web
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      # nodePort: 31515
  selector:
    component: web